// File where all the schema values have been saved
import mongoose, {mongo} from "mongoose";

const schema = new mongoose.Schema({

    // The schema is as given - title, description, createdDate, & lastModifiedDate, id is autogenerated

    // Title defines the task title. The required attribute ensures that the title is added
    title: {
        type: String,
        required: "Title is required"
    },

    // Description defines the description of the task in string format. The required attribute ensures that the description is added
    description: {
        type: String,
        required: "Description is required"
    },

    // The createdDate field contains a date object which gets updated with date of the created task
    createdDate: {
        type: Date,
        default: Date.now
    },

    // The modified date field contains a date object which gets updated with the modified date of the created task
    lastModifiedDate: {
        type: Date,
        default: Date.now
    }

    // Versionkey is kept as false to prevent versioning updates of the document by mongoose and it is only updated on save
 }, {versionKey: false});

 const model = mongoose.model('todolist', schema);
 export default model;